stages:
  preprocess:
    cmd: python preprocess.py data/train.csv data/processed
    deps:
    - data/train.csv
    - preprocess.py
    outs:
    - data/processed
  eda:
    cmd: python eda.py data/train.csv reports/eda
    deps:
    - data/train.csv
    - eda.py
    outs:
    - reports/eda
